import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Captcha from '../components/captcha';
import { useRef } from 'react';
import Reaptcha from 'reaptcha';
import Footer from '../components/footer/Footer';

const Home: NextPage = () => {
  const cref = useRef<Reaptcha | null>();

  const onVerify = (recaptchaResponse: string) => {
    console.log('recaptchaResponse', recaptchaResponse);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div id='form1'>
          <form action="?" method="POST">
            <div>
              <Captcha onValidate={onVerify} />
            </div>
            <br />
            <input type="submit" value="Submit" />
          </form>
        </div>

      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}

export default Home
